[tool.black]
target-version = ['py37', 'py38', 'py39', 'py310']
force-exclude = "{{cookiecutter.project_directory}"

[tool.isort]
profile = "black"
skip = "{{cookiecutter.project_directory}}"

[tool.pytest.ini_options]
addopts = "-v --tb=short --instafail"
testpaths = "tests"
