[tool.pytest.ini_options]
addopts = "-n auto"
testpaths = "tests"


[tool.ruff]
extend = "ruff_defaults.toml"

target-version = "py38"
unfixable = [
    "F401", # unused imports
    "F841", # unused variables
]
