[tool.black]
target-version = ['py37', 'py38', 'py39', 'py310']
exclude = '''
(
  /(
    | \.git
    | env
    | \.env
    | venv
    | \.venv
  )/
)
'''
force-exclude = "{{cookiecutter.project_directory}"

[tool.isort]
profile = "black"
skip = "{{cookiecutter.project_directory}}"

[tool.pytest.ini_options]
addopts = "-v --tb=short"
testpaths = "tests"
