name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tox:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tox-env:
          - py38
          - py39
          - black-template

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U tox
      - name: Tox ${{ matrix.tox-env }}
        run: tox -e ${{ matrix.tox-env }}
